spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cro_prod
    username: cro_prod_user
    password: cro
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
